### ISSUE TITLE
Support for LSTMCell

### ISSUE THREAD

**Issue by rjfnobre** [microsoft/microxcaling#12]
It seems that there is currently no support for torch.nn.LSTMCell.

Is there a simple workaround to adapt code with LSTMCell to enable use the microxscaling library?

**Comment by rizhao-msft** [comment]
We have an implementation for nn.LSTM that we didn't include in the initial release. Would that be enough?

**Comment by rjfnobre** [comment]
Thank you for including the implementation for nn.LSTM.
I believe it will be helpful for many people.

You can close this thread.
