### ISSUE TITLE
Error from test_conv.py and convolution.py to the latest version

### ISSUE THREAD

**Issue by zks878** [microsoft/microxcaling#14]
Originally, when I tested the file version from November 8th, everything was normal.
However, after updating the file to the latest version (Dec 8, 2023), problems arose.

When running the pytest, "test_conv.py" displays
```
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```
The same error also occurs in the "convolution.py" layer within the model.

I copied an unmodified version of the file again, but the error still occurs. 
I'm wondering if anyone has encountered the same issue and how it was resolved. 
Thank you!

**Comment by rizhao-msft** [comment]
Great catch, this should be fixed in 9474171.
