### ISSUE TITLE
Could You Offer a More Comprehensive Environment Setup Guide?

### ISSUE THREAD

**Issue by Mr-Philo** [microsoft/microxcaling#16]
Hi, firstly I want to extend my sincere thanks for the work you've done on MXFP. It has been a valuable resource for the community.

I am reaching out to request **an update to the installation instructions** provided in the README file. Currently the README outlines the basic requirements for the setup, particularly the necessity of `CUDA` (11.3+ recommended) and a reference to the requirements.txt file for Python packages. 

However, README doesn't provide a complete installation procedure, especially for the cpp extension. Add the `pytorch` version, `CUDA` version, `g++` version may confict with each other if not specified. There may be problems when users trying to build custom CUDA extensions using `python build.py install`.

Besides, it would be nice to have mirrors or docker containers with complete environments.

I believe that a more detailed installation guide would be greatly beneficial, especially for those who want to look deeper into MXFP. Thank you again!

**Comment by gakolhe** [comment]
We recommend using [Nvidia-PyTorch Container] (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)
This should take care of most of the dependencies if not all.
Then just perform ```python install .``` under microxcaling directory.
The readme has been updated with installation instructions.
