### ISSUE TITLE
BFloat16 compatibility contributions

### ISSUE THREAD

**Issue by hmellor** [microsoft/microxcaling#21]
Would you be open to contributions that improve support for BFloat16?

Examples:
- If `bfloat: 16` and device supports `torch.bfloat16`, cast instead of emulate
- Allow custom CUDA to work with `torch.bfloat16` tensors:
  - Af first by casting them to `float`, performing the operation, then casting them back to `bfloat16`
  - Then, where applicable, adding BFloat16 operations to speed up emulation. (I believe this should be possible for MX types with `scale_bits <= 8` and element formats which use <=8 bits)

**Comment by gakolhe** [comment]
Most of the suggestions have been incorporated.
