### ISSUE TITLE
MXINT8 elements: MX spec: 2's complement  vs.  README: sign-magnitude

### ISSUE THREAD

**Issue by grayresearch** [microsoft/microxcaling#3]
MX spec 5.3.4 INT8: "... Integer data types use a 2’s complement encoding, but ..." disagrees with
README.md: “MXINT uses sign-magnitude representation, not 2's complement. ...."

**Comment by rizhao-msft** [comment]
Fixed in commit bd54bb6b5cc10d60e892729cf847f01e2f37256c.

**Comment by rizhao-msft** [comment]
Fixed in commit bd54bb6b5cc10d60e892729cf847f01e2f37256c.
