### ISSUE TITLE
Can this library support flash attention?

### ISSUE THREAD

**Issue by ryusaeba** [microsoft/microxcaling#34]
As [flash attention](https://github.com/Dao-AILab/flash-attention/blob/c1d146cbd5becd9e33634b1310c2d27a49c7e862/flash_attn/flash_attn_interface.py#L136) shows, I guess this library cannot support flash attention usage, since mx_mapping.inject_pyt_ops mainly affect the pytorch ops or module. Please correct me if I am wrong.

**Comment by gakolhe** [comment]
You're correct. The library won't quantize the flash-attention ops.
